version: '3.8'
services:
  base-api:
    image: base-api
    build: .
    container_name: base-api
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - postgres
      - elasticsearch
    env_file:
        - .envs/.base-api.env

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
        - .envs/.postgres.env

  elasticsearch:
    image: elasticsearch:7.17.0
    volumes:
      - /var/lib/elasticsearch/data
    ports:
      - 9200:9200
    expose:
      - 9200
    depends_on:
      - kibana
    env_file:
        - .envs/.elasticsearch.env
    deploy:
      resources:
        limits:
          memory: 2048M

  kibana:
    image: kibana:7.17.0
    env_file:
        - .envs/.kibana.env
    ports:
      - 5601:5601
