module.exports = {
  async up(queryInterface, Sequelize) {
    const jobs = [
      {
        description: 'work',
        price: 200,
        paid: false,
        contract_id: 1,
        created_at: Sequelize.literal('CURRENT_TIMESTAMP'),
        updated_at: Sequelize.literal('CURRENT_TIMESTAMP'),
      },
      {
        description: 'work',
        price: 201,
        paid: false,
        contract_id: 2,
        created_at: Sequelize.literal('CURRENT_TIMESTAMP'),
        updated_at: Sequelize.literal('CURRENT_TIMESTAMP'),
      },
      {
        description: 'work',
        price: 202,
        paid: false,
        contract_id: 3,
        created_at: Sequelize.literal('CURRENT_TIMESTAMP'),
        updated_at: Sequelize.literal('CURRENT_TIMESTAMP'),
      },
      {
        description: 'work',
        price: 200,
        paid: false,
        contract_id: 4,
        created_at: Sequelize.literal('CURRENT_TIMESTAMP'),
        updated_at: Sequelize.literal('CURRENT_TIMESTAMP'),
      },
      {
        description: 'work',
        price: 200,
        paid: false,
        contract_id: 7,
        created_at: Sequelize.literal('CURRENT_TIMESTAMP'),
        updated_at: Sequelize.literal('CURRENT_TIMESTAMP'),
      },
      {
        description: 'work',
        price: 2020,
        paid: true,
        payment_date: new Date('2020-08-15T19:11:26.737Z'),
        contract_id: 7,
        created_at: Sequelize.literal('CURRENT_TIMESTAMP'),
        updated_at: Sequelize.literal('CURRENT_TIMESTAMP'),
      },
      {
        description: 'work',
        price: 200,
        paid: true,
        payment_date: new Date('2020-08-15T19:11:26.737Z'),
        contract_id: 2,
        created_at: Sequelize.literal('CURRENT_TIMESTAMP'),
        updated_at: Sequelize.literal('CURRENT_TIMESTAMP'),
      },
      {
        description: 'work',
        price: 200,
        paid: true,
        payment_date: new Date('2020-08-16T19:11:26.737Z'),
        contract_id: 3,
        created_at: Sequelize.literal('CURRENT_TIMESTAMP'),
        updated_at: Sequelize.literal('CURRENT_TIMESTAMP'),
      },
      {
        description: 'work',
        price: 200,
        paid: true,
        payment_date: new Date('2020-08-17T19:11:26.737Z'),
        contract_id: 1,
        created_at: Sequelize.literal('CURRENT_TIMESTAMP'),
        updated_at: Sequelize.literal('CURRENT_TIMESTAMP'),
      },
      {
        description: 'work',
        price: 200,
        paid: true,
        payment_date: new Date('2020-08-17T19:11:26.737Z'),
        contract_id: 5,
        created_at: Sequelize.literal('CURRENT_TIMESTAMP'),
        updated_at: Sequelize.literal('CURRENT_TIMESTAMP'),
      },
      {
        description: 'work',
        price: 21,
        paid: true,
        payment_date: new Date('2020-08-10T19:11:26.737Z'),
        contract_id: 1,
        created_at: Sequelize.literal('CURRENT_TIMESTAMP'),
        updated_at: Sequelize.literal('CURRENT_TIMESTAMP'),
      },
      {
        description: 'work',
        price: 21,
        paid: true,
        payment_date: new Date('2020-08-15T19:11:26.737Z'),
        contract_id: 2,
        created_at: Sequelize.literal('CURRENT_TIMESTAMP'),
        updated_at: Sequelize.literal('CURRENT_TIMESTAMP'),
      },
      {
        description: 'work',
        price: 121,
        paid: true,
        payment_date: new Date('2020-08-15T19:11:26.737Z'),
        contract_id: 3,
        created_at: Sequelize.literal('CURRENT_TIMESTAMP'),
        updated_at: Sequelize.literal('CURRENT_TIMESTAMP'),
      },
      {
        description: 'work',
        price: 121,
        paid: true,
        payment_date: new Date('2020-08-14T23:11:26.737Z'),
        contract_id: 3,
        created_at: Sequelize.literal('CURRENT_TIMESTAMP'),
        updated_at: Sequelize.literal('CURRENT_TIMESTAMP'),
      },
    ]

    await queryInterface.bulkInsert('jobs', jobs, {})
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('jobs', null, {})
  },
}
